
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

#ifeq ($(CONFIG_MTK_CM36652_NEW),y)
#obj-y	+=  cm36652-new/
#endif
#ifeq ($(CONFIG_MTK_AP3XX6_MTK),y)
obj-y	+=  ap3xx6_mtk/
#endif

